### ISSUE TITLE
omicsNPC - dataMapping AND allCombinations arguments - do we need both?

### ISSUE THREAD

**Issue by NestorasK** [lunacab/STATegRa#10]

**Comment by vlagani** [comment]
YES! :-) allCombinations actually indicates that pvaluesNPC must be computed for each combination of the omics datasets; let's say you have three datasets, when allCombinations == TRUE then pvaluesNPC is computed for
dataset1 - dataset2
dataset1 - dataset3
dataset2 - dataset3
dataset1 -dataset2 - dataset3
