### ISSUE TITLE
Building package - error

### ISSUE THREAD

**Issue by NestorasK** [lunacab/STATegRa#3]
I was not able to build the package

**Comment by nuplanell** [comment]
The updated version is the release 3.7, this should work. Which error are you getting?

**Comment by NestorasK** [comment]
I am getting the latest code from github.

Some more details on the error:
I am going to 
*-> Build*
and then I click on 
*-> Install and Restart*
and this is the output

==> R CMD INSTALL --preclean --no-multiarch --with-keep.source STATegRa

* installing to library ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library’
* installing *source* package ‘STATegRa’ ...
** R
Error in .install_package_code_files(".", instdir) : 
files in '/Users/nxk070/Documents/Projects/STATegRa/R' missing from 'Collate' field:
  STATegRa_omicsNPC_ancillaryFunctions.R
  STATegRa_omicsPC.R
  STATegRa_omicsPC_internal.R
ERROR: unable to collate and parse R files for package ‘STATegRa’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/STATegRa’

Exited with status 1.

**Comment by nuplanell** [comment]
Are you using RStudio to build the package?

**Comment by NestorasK** [comment]
Yes
I am adding also my R version's and platform information.

platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          4.2                         
year           2017                        
month          09                          
day            28                          
svn rev        73368                       
language       R                           
version.string R version 3.4.2 (2017-09-28)
nickname       Short Summer

**Comment by NestorasK** [comment]
My bad, I was trying to build the package, being in a new branch and not on the master branch. 
Sorry for the confusion. I am closing this issue. 

Being in master branch worked fine. 
I manage to build it

**Comment by nuplanell** [comment]
ok! don't worry. Try with the master and if it doesn't work just tell me.
